Test config on the example production next.js app with both success and failing rules

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -54,9 +54,23 @@ jobs:
           node-version: 20
           cache: pnpm
       - run: pnpm install
-      - run: cd ts-next-app && pnpm run lint ./src
+      - run: cd ts-next-app && pnpm run lint:against-clear
+  AppLintTestExpectFailure:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Test lint command that is expected to fail
+        id: failing_step
+        run: |
+          cd ts-next-app && pnpm run lint:against-errors
+        continue-on-error: true
+
+      - name: Finalize lint failure test
+        if: steps.failing_step.outcome == 'success'
+        run: |
+          echo "ESLint does not check errors for some reason"
+          exit 1
   Finalize:
-    needs: [Lint, Types, AppLintTest]
+    needs: [Lint, Types, AppLintTest,AppLintTestExpectFailure]
     runs-on: ubuntu-latest
     steps:
       - name: Success
